version: '3'

services:
  kuaishou-admin-vue:
    # 从当前路径构建镜像
    build:
      context: .
      dockerfile: Dockerfile
    image: kuaishou-admin-vue
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
